# Copyright 2017 ZT Prentner IT GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# German translations for RKTool package.
msgid ""
msgstr ""
"Project-Id-Version: 0.1\n"
"POT-Creation-Date: 2017-03-29 12:24+CEST\n"
"PO-Revision-Date: 2016-05-30 23:05+0200\n"
"Last-Translator: Mino Sharkhawy\n"
"Language-Team: German\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: cashreg.py:113
msgid "Invalid turnover counter size."
msgstr "Umsatzzähler-Länge ungültig."

#: cashreg.py:156 main.py:411 receipt.py:96 rktool.py:411
msgid "Invalid key."
msgstr "Ungültiger Schlüssel."

#: demo.py:83
msgid "The number of receipts must be at least 1."
msgstr "Die Anzahl der Rechnungen muss mindestens 1 sein."

#: main.py:214 rktool.py:214
msgid "Error"
msgstr "Fehler"

#: main.py:289 main.py:361 rktool.py:289 rktool.py:361
msgid "Valid Signature"
msgstr "Gültige Signatur"

#: main.py:294 rktool.py:294
msgid "No Signature"
msgstr "Keine Signatur"

#: main.py:326 rktool.py:326
msgid "Signature system broken"
msgstr "Sicherheitseinrichtung ausgefallen"

#: main.py:328 rktool.py:328
msgid "ZDA ID"
msgstr "ZDA ID"

#: main.py:329 rktool.py:329
msgid "Cash Register ID"
msgstr "Kassen-ID"

#: main.py:330 rktool.py:330
msgid "Receipt ID"
msgstr "Belegnummer"

#: main.py:331 rktool.py:331
msgid "Timestamp"
msgstr "Datum & Uhrzeit"

#: main.py:332 rktool.py:332
msgid "Sum Tax Normal"
msgstr "Betrag Satz Normal"

#: main.py:333 rktool.py:333
msgid "Sum Tax Reduced 1"
msgstr "Betrag Satz Ermäßigt 1"

#: main.py:334 rktool.py:334
msgid "Sum Tax Reduced 2"
msgstr "Betrag Satz Ermäßigt 2"

#: main.py:335 rktool.py:335
msgid "Sum Tax Zero"
msgstr "Betrag Satz Null"

#: main.py:336 rktool.py:336
msgid "Sum Tax Special"
msgstr "Betrag Satz Besonders"

#: main.py:337 rktool.py:337
msgid "Turnover Counter"
msgstr "Umsatzzähler"

#: main.py:338 rktool.py:338
msgid "Certificate Serial/Key ID"
msgstr "Zertifikat-Seriennummer/Schlüssel ID"

#: main.py:339 rktool.py:339
msgid "Chaining Value"
msgstr "Verkettungswert"

#: main.py:340 rktool.py:340
msgid "Signature"
msgstr "Signatur"

#: main.py:345 main.py:694 rktool.py:345 rktool.py:694
msgid "Verifying..."
msgstr "Überprüfe..."

#: main.py:355 main.py:675 main.py:708 main.py:723 main.py:739 rktool.kv:145
#: rktool.kv:248 rktool.py:355 rktool.py:675 rktool.py:708 rktool.py:723
#: rktool.py:739
msgid "Verify"
msgstr "Überprüfen"

#: main.py:374 main.py:783 rktool.kv:233 rktool.py:374 rktool.py:783
msgid "Load AES Key"
msgstr "AES Schlüssel laden"

#: main.py:395 main.py:803 main.py:953 rktool.py:395 rktool.py:803
#: rktool.py:953
msgid "Malformed crypto container"
msgstr "Ungültiges Schlüsselmaterial"

#: main.py:456 rktool.py:456
msgid "No image taken."
msgstr "Kein Bild aufgenommen."

#: main.py:465 rktool.py:465
msgid "Failed to compress image."
msgstr "Fehler beim Komprimieren des Bildes."

#: main.py:484 main.py:505 rktool.py:484 rktool.py:505
msgid "No QR codes found."
msgstr "Keine QR-Codes gefunden."

#: main.py:492 rktool.py:492
msgid "Load Receipt"
msgstr "Rechnung laden"

#: main.py:627 rktool.py:627
msgid "Group %d"
msgstr "Gruppe %d"

#: main.py:639 main.py:646 main.py:846 rktool.py:639 rktool.py:646
#: rktool.py:846
msgid "Serial: "
msgstr "Seriennummer: "

#: main.py:745 rktool.py:745
msgid "Valid DEP"
msgstr "Gültiges DEP"

#: main.py:754 rktool.kv:230 rktool.py:754
msgid "Load DEP"
msgstr "DEP laden"

#: main.py:814 rktool.py:814
msgid "Public Keys"
msgstr "Öffentliche Schlüssel"

#: main.py:816 rktool.py:816
msgid "Certificates"
msgstr "Zertifikate"

#: main.py:851 rktool.py:851
msgid "Key ID: "
msgstr "Schlüssel ID: "

#: main.py:864 rktool.py:864
msgid "Load PEM Public Key"
msgstr "Öffentlichen Schlüssel (PEM) laden"

#: main.py:869 rktool.py:869
msgid "Load PEM Certificate"
msgstr "Zertifikat (PEM) laden "

#: main.py:890 rktool.py:890
msgid "Enter Public Key ID"
msgstr "ID des öffentlichen Schlüssels eingeben"

#: main.py:920 rktool.py:920
msgid "Load Key Store"
msgstr "Schlüsselspeicher laden"

#: main.py:926 rktool.py:926
msgid "Save Key Store"
msgstr "Schlüsselspeicher speichern"

#: receipt.py:44 verify.py:101
msgid "At receipt \"{0}\": {1}"
msgstr "Bei Rechnung \"{0}\": {1}"

#: receipt.py:68
msgid "Malformed receipt."
msgstr "Ungültige Rechnung."

#: receipt.py:78
msgid "Unknown algorithm."
msgstr "Unbekannter Algorithmus."

#: receipt.py:87
msgid "Algorithm mismatch."
msgstr "Inkompatible Algorithmen."

#: receipt.py:131
msgid "Unknown Receipt"
msgstr "Unbekannte Rechnung."

#: receipt.py:285 receipt.py:389 receipt.py:444 receipt.py:539
msgid "You need to sign the receipt first."
msgstr "Die Rechnung muss zuerst signiert werden."

#: receipt.py:579
msgid "Can't decrypt turnover counter, this is a dummy receipt."
msgstr "Kann Umsatzzähler nicht entschlüsseln. Dies ist ein Trainingsbeleg."

#: receipt.py:581
msgid "Can't decrypt turnover counter, this is a reversal receipt."
msgstr "Kann Umsatzzähler nicht entschlüsseln. Dies ist ein Stornobeleg."

#: receipt.py:617 verify_receipt.py:413
msgid "Input format must be one of %s."
msgstr "Eingabeformat muss eines aus %s sein."

#: receipt.py:621
msgid "Output format must be one of %s."
msgstr "Ausgabeformat muss eines aus %s sein."

#: rktool.kv:52 rktool.kv:75 rktool.kv:93
msgid "Cancel"
msgstr "Abbrechen"

#: rktool.kv:55
msgid "Load"
msgstr "Laden"

#: rktool.kv:78
msgid "Save"
msgstr "Speichern"

#: rktool.kv:96
msgid "Ok"
msgstr "Ok"

#: rktool.kv:128
msgid "Receipt"
msgstr "Rechnung"

#: rktool.kv:132 rktool.kv:286
msgid "Exit"
msgstr "Beenden"

#: rktool.kv:149
msgid "Decrypt Turnover Counter"
msgstr "Umsatzzähler entschlüsseln"

#: rktool.kv:197
msgid "JWS string"
msgstr "JWS-Zeichenkette"

#: rktool.kv:203
msgid "QR code"
msgstr "QR-Code"

#: rktool.kv:208
msgid "OCR code"
msgstr "OCR-Code"

#: rktool.kv:213
msgid "URL"
msgstr "URL"

#: rktool.kv:217
msgid "Read Receipt"
msgstr "Rechnung lesen"

#: rktool.kv:268
msgid "Import"
msgstr "Importieren"

#: rktool.kv:271
msgid "Export"
msgstr "Exportieren"

#: rktool.kv:279
msgid "Registrierkassen Tool"
msgstr "Registrierkassen Tool"

#: rktool.kv:298
msgid "Verify Receipt"
msgstr "Rechnung überprüfen"

#: rktool.kv:302
msgid "Verify DEP"
msgstr "DEP überprüfen"

#: rktool.kv:306
msgid "Key Store"
msgstr "Schlüsselspeicher"

#: run_test.py:64
msgid "Need key material for {} signature devices, got {} key pairs."
msgstr ""
"Brauche Schlüsselmaterial für {} Sicherheitseinrichtungen, habe {} "
"Schlüsselpaare bekommen."

#: run_test.py:270
msgid "I need keys and certificates for %d signature devices."
msgstr "Ich brauche Schlüssel und Zertifikate für %d Sicherheitseinrichtungen."

#: run_test.py:282 test_verify.py:266
msgid "Turnover counter size needs to be between 5 and 16."
msgstr "Umsatzzähler-Länge muss zwischen 5 und 16 sein."

#: sigsys.py:154
msgid "Selected algorithm not supported."
msgstr "Gewählter Algorithmus wird nicht unterstützt."

#: test_verify.py:72 test_verify.py:75 test_verify.py:80
msgid "no Exception"
msgstr "kein Fehler"

#: test_verify.py:116
msgid "State update without verification failed."
msgstr "Zustandsupdate ohne Verifikation fehlgeschlagen."

#: test_verify.py:125
msgid "Expected {} in turnover counter but got {}."
msgstr "Erwartete {} im Umsatzzähler, aber habe {} bekommen."

#: test_verify.py:138
msgid "Expected \"{}\" but got \"{}\", message: \"{}\""
msgstr "Erwartete \"{}\", aber habe \"{}\" bekommen, Nachricht: \"{}\""

#: test_verify.py:145
msgid "Expected \"{}\" at receipt \"{}\" but it occured at \"{}\" instead"
msgstr ""
"Erwartete \"{}\" bei Rechnung \"{}\", aber habe es stattdessen bei \"{}\" "
"bekommen"

#: test_verify.py:189
msgid "Result mismatch: without parsing {}:>{}<, with parsing {}:>{}<"
msgstr "Ergebnisse verschieden: ohne parsing {}:>{}<, mit parsing {}:>{}<"

#: test_verify.py:227
msgid "No run label"
msgstr "Kein Simulationsname"

#: test_verify.py:244
msgid "{} tests run, {} failed, {} errors"
msgstr "{} Tests ausgeführt, {} fehlgeschlagen, {} Fehler"

#: verification_state.py:45
msgid "No cash register with index {}."
msgstr "Keine Kassa mit Index {}."

#: verification_state.py:51
msgid "The last cash register has no registered start receipt."
msgstr "Die letzte Kassa hat keinen registrierten Startbeleg."

#: verification_state.py:130
msgid "Start Receipt"
msgstr "Startbeleg"

#: verification_state.py:131
msgid "Last Receipt"
msgstr "Letzter Beleg"

#: verification_state.py:132
msgid "Last Turnover Counter"
msgstr "Letzter Umsatzzähler"

#: verification_state.py:133
msgid "Need Restore Receipt"
msgstr "Benötigt Nullbeleg"

#: verification_state.py:238
msgid "Cash Register {}:"
msgstr "Kassa {}:"

#: verification_state.py:241
msgid "Used Receipt IDs"
msgstr "Benutzte Belegnummern"

#: verify.py:59
msgid "Malformed DEP"
msgstr "Ungültiges DEP"

#: verify.py:69
msgid "Malformed certificate: \"{}\""
msgstr "Ungültiges Zertifikat: \"{}\""

#: verify.py:79
msgid "Element \"{}\" missing from DEP"
msgstr "Element \"{}\" fehlt in DEP"

#: verify.py:90
msgid "GGS Cluster is not supported in an open system."
msgstr "GGS Verbund wird in offenen Systemen nicht unterstützt."

#: verify.py:113
msgid "Previous receipt is not \"{0}\"."
msgstr "Vorherige Rechnung ist nicht \"{0}\"."

#: verify.py:125
msgid "Receipt after restored signature system must not have any turnover."
msgstr ""
"Rechnung nach Wiederherstellung der Sicherheitseinrichtung darf keinen "
"Umsatz haben."

#: verify.py:136
msgid "Receipt ID already in use."
msgstr "Rechnungs-ID wird bereits verwendet."

#: verify.py:146
msgid "Turnover counter invalid."
msgstr "Umsatzzähler ungültig."

#: verify.py:156
msgid "Register ID changed."
msgstr "Kassen-ID geändert."

#: verify.py:167
msgid "Receipt was created before previous receipt."
msgstr "Rechnung wurde vor vorhergehender Rechnung erstellt."

#: verify.py:178
msgid "The system type changed."
msgstr "Typ des Systems wurde geändert."

#: verify.py:189
msgid "The size of the turnover counter changed."
msgstr "Die Länge des Umsatzzählers wurde geändert."

#: verify.py:199
msgid "No certificate specified in DEP and multiple groups used."
msgstr "Kein Zertifikat angegeben, aber DEP hat mehrere Gruppen."

#: verify.py:211
msgid "Certificate \"%s\" is not trusted."
msgstr "Zertifikat \"%s\" wird nicht vertraut."

#: verify.py:223
msgid "Certificate \"{}\" was not signed by \"{}\"."
msgstr "Zertifikat \"{}\" wurde nicht von \"{}\" signiert."

#: verify.py:235
msgid ""
"Two certificates with serial \"{0}\" detected (fingerprints \"{1}\" and "
"\"{2}\"). This may be an attempted attack."
msgstr ""
"Zwei Zertifikate mit Seriennummer \"{0}\" gefunden (Fingerabdrücke \"{1}\" "
"und \"{2}\"). Dies könnte ein versuchter Angriff sein."

#: verify.py:245
msgid "Initial receipt not signed."
msgstr "Startbeleg nicht signiert."

#: verify.py:254
msgid "Initial receipt has nonzero turnover."
msgstr "Startbeleg hat Umsatz ungleich Null."

#: verify.py:265
msgid "Initial receipt has not been chained to the cash register ID."
msgstr "Startbeleg ist nicht mit der Kassen-ID verkettet."

#: verify.py:276
msgid ""
"Initial receipt in cluster has not been chained to the previous cash "
"register's initial receipt."
msgstr ""
"Startbeleg in Verbund ist nicht mit dem Startbeleg der vorherigen Kassa "
"verkettet."

#: verify.py:286
msgid "Initial receipt is a dummy or reversal receipt."
msgstr "Startbeleg ist ein Trainings- oder Storno-Beleg."

#: verify.py:1013
msgid "Verification successful."
msgstr "Überprüfung erfolgreich."

#: verify_receipt.py:42
msgid "Certificate serial mismatch."
msgstr "Zertifikat-Seriennummern stimmen nicht überein."

#: verify_receipt.py:50
msgid "Certificate serial invalid."
msgstr "Zertifikat-Seriennummer ungültig."

#: verify_receipt.py:59
msgid "No public key found."
msgstr "Kein öffentlicher Schlüssel gefunden."

#: verify_receipt.py:67
msgid "Invalid Signature."
msgstr "Ungültige Signatur."

#: verify_receipt.py:77
msgid "{} This is probably fine."
msgstr "{} Das ist wahrscheinlich in Ordnung."

#: verify_receipt.py:86
msgid "Signature System failed."
msgstr "Sicherheitseinrichtung ausgefallen."

#: verify_receipt.py:95
msgid "Invalid URL hash."
msgstr "Ungültige URL Prüfsumme."

#: verify_receipt.py:105
msgid "Invalid certificate provider."
msgstr "Ungültiger Zertifizierungsdiensteanbieter."

#: verify_receipt.py:114
msgid "Null receipt not signed."
msgstr "Nullbeleg nicht signiert."

#: verify_receipt.py:435
msgid "Line {: >3}: {}"
msgstr "Zeile {: >3}: {}"

#: verify_receipt.py:438
msgid "{} of {} receipts verified successfully."
msgstr "{} von {} Rechnungen wurden erfolgreich überprüft."
